name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        python -m pytest --cov=calculator --cov-report=html

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/

  version:
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install bump2version
      run: pip install bump2version

    - name: Configure Git
      run: |
        git config --global user.name 'deltahedge1'
        git config --global user.email 'ihassan1@kpmg.com.au'

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global credential.helper store
        git config --global credential.helper 'cache --timeout=3600'
        echo "machine github.com login YOUR_GITHUB_USERNAME password ${{ secrets.PAT }}" > ~/.netrc
        git remote set-url origin "https://github.com/${{ github.repository }}"
        
    - name: Push version bump
      run: git push origin main